### ISSUE TITLE
Sending values

### ISSUE THREAD

**Issue by Ben1902** [openmucextensions/mqtt-driver#1]
Hello, wonderful driver! Maybe a dumb question, but do I have to use the «OpenMUC Gateway» to write values from another driver out to the mqtt broker? There was little in the readme about channels.. I managed successfully to write to my topic/channel via the manual test tool in openmuc..

**Comment by pichler** [comment]
Hello. Yes you're right. If you want to send vaues from another driver in OpenMUC to the mqtt broker, [OpenMUC Extensions Gateway](https://github.com/openmucextensions/gateway) is the right application for you (together with the mqtt driver). Using this application, you can also receive values from the mqtt broker and write them to another driver (e.g. bacnet).

To get it working, you have to configure OpenMUC channels for the source driver (e.g. a sensor value from bacnet) and also for the mqtt driver (naming the mqtt topic). Information about how to configure channels can be found in the official [OpenMUC user guide](https://www.openmuc.org/openmuc/user-guide/). Afterwands, you can "connect" the channels using the gateway application.

Regards, Mike

**Comment by Ben1902** [comment]
Thank you very much! Works brilliantly!
